// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCookieServiceMock creates a new instance of CookieServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCookieServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CookieServiceMock {
	mock := &CookieServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CookieServiceMock is an autogenerated mock type for the CookieService type
type CookieServiceMock struct {
	mock.Mock
}

type CookieServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CookieServiceMock) EXPECT() *CookieServiceMock_Expecter {
	return &CookieServiceMock_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type CookieServiceMock
func (_mock *CookieServiceMock) Sign(ctx context.Context, value string) string {
	ret := _mock.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, value)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CookieServiceMock_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type CookieServiceMock_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - ctx context.Context
//   - value string
func (_e *CookieServiceMock_Expecter) Sign(ctx interface{}, value interface{}) *CookieServiceMock_Sign_Call {
	return &CookieServiceMock_Sign_Call{Call: _e.mock.On("Sign", ctx, value)}
}

func (_c *CookieServiceMock_Sign_Call) Run(run func(ctx context.Context, value string)) *CookieServiceMock_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CookieServiceMock_Sign_Call) Return(s string) *CookieServiceMock_Sign_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CookieServiceMock_Sign_Call) RunAndReturn(run func(ctx context.Context, value string) string) *CookieServiceMock_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type CookieServiceMock
func (_mock *CookieServiceMock) Verify(ctx context.Context, signedValue string) (string, error) {
	ret := _mock.Called(ctx, signedValue)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, signedValue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, signedValue)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, signedValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CookieServiceMock_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type CookieServiceMock_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - signedValue string
func (_e *CookieServiceMock_Expecter) Verify(ctx interface{}, signedValue interface{}) *CookieServiceMock_Verify_Call {
	return &CookieServiceMock_Verify_Call{Call: _e.mock.On("Verify", ctx, signedValue)}
}

func (_c *CookieServiceMock_Verify_Call) Run(run func(ctx context.Context, signedValue string)) *CookieServiceMock_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CookieServiceMock_Verify_Call) Return(s string, err error) *CookieServiceMock_Verify_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *CookieServiceMock_Verify_Call) RunAndReturn(run func(ctx context.Context, signedValue string) (string, error)) *CookieServiceMock_Verify_Call {
	_c.Call.Return(run)
	return _c
}
