// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewDBTXMock creates a new instance of DBTXMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBTXMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBTXMock {
	mock := &DBTXMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DBTXMock is an autogenerated mock type for the DBTX type
type DBTXMock struct {
	mock.Mock
}

type DBTXMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DBTXMock) EXPECT() *DBTXMock_Expecter {
	return &DBTXMock_Expecter{mock: &_m.Mock}
}

// ExecContext provides a mock function for the type DBTXMock
func (_mock *DBTXMock) ExecContext(context1 context.Context, s string, ifaceVals ...interface{}) (sql.Result, error) {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (sql.Result, error)); ok {
		return returnFunc(context1, s, ifaceVals...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) sql.Result); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = returnFunc(context1, s, ifaceVals...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBTXMock_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type DBTXMock_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - ifaceVals ...interface{}
func (_e *DBTXMock_Expecter) ExecContext(context1 interface{}, s interface{}, ifaceVals ...interface{}) *DBTXMock_ExecContext_Call {
	return &DBTXMock_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *DBTXMock_ExecContext_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *DBTXMock_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DBTXMock_ExecContext_Call) Return(result sql.Result, err error) *DBTXMock_ExecContext_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *DBTXMock_ExecContext_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) (sql.Result, error)) *DBTXMock_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function for the type DBTXMock
func (_mock *DBTXMock) PrepareContext(context1 context.Context, s string) (*sql.Stmt, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *sql.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sql.Stmt, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sql.Stmt); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBTXMock_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type DBTXMock_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *DBTXMock_Expecter) PrepareContext(context1 interface{}, s interface{}) *DBTXMock_PrepareContext_Call {
	return &DBTXMock_PrepareContext_Call{Call: _e.mock.On("PrepareContext", context1, s)}
}

func (_c *DBTXMock_PrepareContext_Call) Run(run func(context1 context.Context, s string)) *DBTXMock_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DBTXMock_PrepareContext_Call) Return(stmt *sql.Stmt, err error) *DBTXMock_PrepareContext_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *DBTXMock_PrepareContext_Call) RunAndReturn(run func(context1 context.Context, s string) (*sql.Stmt, error)) *DBTXMock_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function for the type DBTXMock
func (_mock *DBTXMock) QueryContext(context1 context.Context, s string, ifaceVals ...interface{}) (*sql.Rows, error) {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (*sql.Rows, error)); ok {
		return returnFunc(context1, s, ifaceVals...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.Rows); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = returnFunc(context1, s, ifaceVals...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBTXMock_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type DBTXMock_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - ifaceVals ...interface{}
func (_e *DBTXMock_Expecter) QueryContext(context1 interface{}, s interface{}, ifaceVals ...interface{}) *DBTXMock_QueryContext_Call {
	return &DBTXMock_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *DBTXMock_QueryContext_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *DBTXMock_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DBTXMock_QueryContext_Call) Return(rows *sql.Rows, err error) *DBTXMock_QueryContext_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *DBTXMock_QueryContext_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) (*sql.Rows, error)) *DBTXMock_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function for the type DBTXMock
func (_mock *DBTXMock) QueryRowContext(context1 context.Context, s string, ifaceVals ...interface{}) *sql.Row {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.Row); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// DBTXMock_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type DBTXMock_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - ifaceVals ...interface{}
func (_e *DBTXMock_Expecter) QueryRowContext(context1 interface{}, s interface{}, ifaceVals ...interface{}) *DBTXMock_QueryRowContext_Call {
	return &DBTXMock_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *DBTXMock_QueryRowContext_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *DBTXMock_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DBTXMock_QueryRowContext_Call) Return(row *sql.Row) *DBTXMock_QueryRowContext_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *DBTXMock_QueryRowContext_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) *sql.Row) *DBTXMock_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}
