// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/voxel-api/internal/infra/notification"
	mock "github.com/stretchr/testify/mock"
)

// NewEmailNotificationMock creates a new instance of EmailNotificationMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailNotificationMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailNotificationMock {
	mock := &EmailNotificationMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmailNotificationMock is an autogenerated mock type for the EmailNotification type
type EmailNotificationMock struct {
	mock.Mock
}

type EmailNotificationMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailNotificationMock) EXPECT() *EmailNotificationMock_Expecter {
	return &EmailNotificationMock_Expecter{mock: &_m.Mock}
}

// SendChangeEmailNotification provides a mock function for the type EmailNotificationMock
func (_mock *EmailNotificationMock) SendChangeEmailNotification(ctx context.Context, params notification.SendChangeEmailParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendChangeEmailNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, notification.SendChangeEmailParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailNotificationMock_SendChangeEmailNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendChangeEmailNotification'
type EmailNotificationMock_SendChangeEmailNotification_Call struct {
	*mock.Call
}

// SendChangeEmailNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - params notification.SendChangeEmailParams
func (_e *EmailNotificationMock_Expecter) SendChangeEmailNotification(ctx interface{}, params interface{}) *EmailNotificationMock_SendChangeEmailNotification_Call {
	return &EmailNotificationMock_SendChangeEmailNotification_Call{Call: _e.mock.On("SendChangeEmailNotification", ctx, params)}
}

func (_c *EmailNotificationMock_SendChangeEmailNotification_Call) Run(run func(ctx context.Context, params notification.SendChangeEmailParams)) *EmailNotificationMock_SendChangeEmailNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 notification.SendChangeEmailParams
		if args[1] != nil {
			arg1 = args[1].(notification.SendChangeEmailParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmailNotificationMock_SendChangeEmailNotification_Call) Return(err error) *EmailNotificationMock_SendChangeEmailNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailNotificationMock_SendChangeEmailNotification_Call) RunAndReturn(run func(ctx context.Context, params notification.SendChangeEmailParams) error) *EmailNotificationMock_SendChangeEmailNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendMagicLinkEmail provides a mock function for the type EmailNotificationMock
func (_mock *EmailNotificationMock) SendMagicLinkEmail(ctx context.Context, params notification.SendMagicLinkEmailParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendMagicLinkEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, notification.SendMagicLinkEmailParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailNotificationMock_SendMagicLinkEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMagicLinkEmail'
type EmailNotificationMock_SendMagicLinkEmail_Call struct {
	*mock.Call
}

// SendMagicLinkEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - params notification.SendMagicLinkEmailParams
func (_e *EmailNotificationMock_Expecter) SendMagicLinkEmail(ctx interface{}, params interface{}) *EmailNotificationMock_SendMagicLinkEmail_Call {
	return &EmailNotificationMock_SendMagicLinkEmail_Call{Call: _e.mock.On("SendMagicLinkEmail", ctx, params)}
}

func (_c *EmailNotificationMock_SendMagicLinkEmail_Call) Run(run func(ctx context.Context, params notification.SendMagicLinkEmailParams)) *EmailNotificationMock_SendMagicLinkEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 notification.SendMagicLinkEmailParams
		if args[1] != nil {
			arg1 = args[1].(notification.SendMagicLinkEmailParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmailNotificationMock_SendMagicLinkEmail_Call) Return(err error) *EmailNotificationMock_SendMagicLinkEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailNotificationMock_SendMagicLinkEmail_Call) RunAndReturn(run func(ctx context.Context, params notification.SendMagicLinkEmailParams) error) *EmailNotificationMock_SendMagicLinkEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendResetPasswordEmail provides a mock function for the type EmailNotificationMock
func (_mock *EmailNotificationMock) SendResetPasswordEmail(ctx context.Context, params notification.SendResetPasswordEmailParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendResetPasswordEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, notification.SendResetPasswordEmailParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailNotificationMock_SendResetPasswordEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendResetPasswordEmail'
type EmailNotificationMock_SendResetPasswordEmail_Call struct {
	*mock.Call
}

// SendResetPasswordEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - params notification.SendResetPasswordEmailParams
func (_e *EmailNotificationMock_Expecter) SendResetPasswordEmail(ctx interface{}, params interface{}) *EmailNotificationMock_SendResetPasswordEmail_Call {
	return &EmailNotificationMock_SendResetPasswordEmail_Call{Call: _e.mock.On("SendResetPasswordEmail", ctx, params)}
}

func (_c *EmailNotificationMock_SendResetPasswordEmail_Call) Run(run func(ctx context.Context, params notification.SendResetPasswordEmailParams)) *EmailNotificationMock_SendResetPasswordEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 notification.SendResetPasswordEmailParams
		if args[1] != nil {
			arg1 = args[1].(notification.SendResetPasswordEmailParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmailNotificationMock_SendResetPasswordEmail_Call) Return(err error) *EmailNotificationMock_SendResetPasswordEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailNotificationMock_SendResetPasswordEmail_Call) RunAndReturn(run func(ctx context.Context, params notification.SendResetPasswordEmailParams) error) *EmailNotificationMock_SendResetPasswordEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendVerifyEmail provides a mock function for the type EmailNotificationMock
func (_mock *EmailNotificationMock) SendVerifyEmail(ctx context.Context, params notification.SendVerifyEmailParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendVerifyEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, notification.SendVerifyEmailParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailNotificationMock_SendVerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerifyEmail'
type EmailNotificationMock_SendVerifyEmail_Call struct {
	*mock.Call
}

// SendVerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - params notification.SendVerifyEmailParams
func (_e *EmailNotificationMock_Expecter) SendVerifyEmail(ctx interface{}, params interface{}) *EmailNotificationMock_SendVerifyEmail_Call {
	return &EmailNotificationMock_SendVerifyEmail_Call{Call: _e.mock.On("SendVerifyEmail", ctx, params)}
}

func (_c *EmailNotificationMock_SendVerifyEmail_Call) Run(run func(ctx context.Context, params notification.SendVerifyEmailParams)) *EmailNotificationMock_SendVerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 notification.SendVerifyEmailParams
		if args[1] != nil {
			arg1 = args[1].(notification.SendVerifyEmailParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmailNotificationMock_SendVerifyEmail_Call) Return(err error) *EmailNotificationMock_SendVerifyEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailNotificationMock_SendVerifyEmail_Call) RunAndReturn(run func(ctx context.Context, params notification.SendVerifyEmailParams) error) *EmailNotificationMock_SendVerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendWelcomeEmail provides a mock function for the type EmailNotificationMock
func (_mock *EmailNotificationMock) SendWelcomeEmail(ctx context.Context, params notification.SendWelcomeEmailParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendWelcomeEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, notification.SendWelcomeEmailParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailNotificationMock_SendWelcomeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWelcomeEmail'
type EmailNotificationMock_SendWelcomeEmail_Call struct {
	*mock.Call
}

// SendWelcomeEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - params notification.SendWelcomeEmailParams
func (_e *EmailNotificationMock_Expecter) SendWelcomeEmail(ctx interface{}, params interface{}) *EmailNotificationMock_SendWelcomeEmail_Call {
	return &EmailNotificationMock_SendWelcomeEmail_Call{Call: _e.mock.On("SendWelcomeEmail", ctx, params)}
}

func (_c *EmailNotificationMock_SendWelcomeEmail_Call) Run(run func(ctx context.Context, params notification.SendWelcomeEmailParams)) *EmailNotificationMock_SendWelcomeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 notification.SendWelcomeEmailParams
		if args[1] != nil {
			arg1 = args[1].(notification.SendWelcomeEmailParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmailNotificationMock_SendWelcomeEmail_Call) Return(err error) *EmailNotificationMock_SendWelcomeEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailNotificationMock_SendWelcomeEmail_Call) RunAndReturn(run func(ctx context.Context, params notification.SendWelcomeEmailParams) error) *EmailNotificationMock_SendWelcomeEmail_Call {
	_c.Call.Return(run)
	return _c
}
