// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gbvillarinho/base-project/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewEmailServiceMock creates a new instance of EmailServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailServiceMock {
	mock := &EmailServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmailServiceMock is an autogenerated mock type for the EmailService type
type EmailServiceMock struct {
	mock.Mock
}

type EmailServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailServiceMock) EXPECT() *EmailServiceMock_Expecter {
	return &EmailServiceMock_Expecter{mock: &_m.Mock}
}

// SendChangeEmailAsync provides a mock function for the type EmailServiceMock
func (_mock *EmailServiceMock) SendChangeEmailAsync(ctx context.Context, user *domain.User, verification *domain.Verification) {
	_mock.Called(ctx, user, verification)
	return
}

// EmailServiceMock_SendChangeEmailAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendChangeEmailAsync'
type EmailServiceMock_SendChangeEmailAsync_Call struct {
	*mock.Call
}

// SendChangeEmailAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - verification *domain.Verification
func (_e *EmailServiceMock_Expecter) SendChangeEmailAsync(ctx interface{}, user interface{}, verification interface{}) *EmailServiceMock_SendChangeEmailAsync_Call {
	return &EmailServiceMock_SendChangeEmailAsync_Call{Call: _e.mock.On("SendChangeEmailAsync", ctx, user, verification)}
}

func (_c *EmailServiceMock_SendChangeEmailAsync_Call) Run(run func(ctx context.Context, user *domain.User, verification *domain.Verification)) *EmailServiceMock_SendChangeEmailAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 *domain.Verification
		if args[2] != nil {
			arg2 = args[2].(*domain.Verification)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmailServiceMock_SendChangeEmailAsync_Call) Return() *EmailServiceMock_SendChangeEmailAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *EmailServiceMock_SendChangeEmailAsync_Call) RunAndReturn(run func(ctx context.Context, user *domain.User, verification *domain.Verification)) *EmailServiceMock_SendChangeEmailAsync_Call {
	_c.Run(run)
	return _c
}

// SendMagicLinkEmailAsync provides a mock function for the type EmailServiceMock
func (_mock *EmailServiceMock) SendMagicLinkEmailAsync(ctx context.Context, user *domain.User, verification *domain.Verification) {
	_mock.Called(ctx, user, verification)
	return
}

// EmailServiceMock_SendMagicLinkEmailAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMagicLinkEmailAsync'
type EmailServiceMock_SendMagicLinkEmailAsync_Call struct {
	*mock.Call
}

// SendMagicLinkEmailAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - verification *domain.Verification
func (_e *EmailServiceMock_Expecter) SendMagicLinkEmailAsync(ctx interface{}, user interface{}, verification interface{}) *EmailServiceMock_SendMagicLinkEmailAsync_Call {
	return &EmailServiceMock_SendMagicLinkEmailAsync_Call{Call: _e.mock.On("SendMagicLinkEmailAsync", ctx, user, verification)}
}

func (_c *EmailServiceMock_SendMagicLinkEmailAsync_Call) Run(run func(ctx context.Context, user *domain.User, verification *domain.Verification)) *EmailServiceMock_SendMagicLinkEmailAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 *domain.Verification
		if args[2] != nil {
			arg2 = args[2].(*domain.Verification)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmailServiceMock_SendMagicLinkEmailAsync_Call) Return() *EmailServiceMock_SendMagicLinkEmailAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *EmailServiceMock_SendMagicLinkEmailAsync_Call) RunAndReturn(run func(ctx context.Context, user *domain.User, verification *domain.Verification)) *EmailServiceMock_SendMagicLinkEmailAsync_Call {
	_c.Run(run)
	return _c
}

// SendResetPasswordEmailAsync provides a mock function for the type EmailServiceMock
func (_mock *EmailServiceMock) SendResetPasswordEmailAsync(ctx context.Context, user *domain.User, verification *domain.Verification) {
	_mock.Called(ctx, user, verification)
	return
}

// EmailServiceMock_SendResetPasswordEmailAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendResetPasswordEmailAsync'
type EmailServiceMock_SendResetPasswordEmailAsync_Call struct {
	*mock.Call
}

// SendResetPasswordEmailAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - verification *domain.Verification
func (_e *EmailServiceMock_Expecter) SendResetPasswordEmailAsync(ctx interface{}, user interface{}, verification interface{}) *EmailServiceMock_SendResetPasswordEmailAsync_Call {
	return &EmailServiceMock_SendResetPasswordEmailAsync_Call{Call: _e.mock.On("SendResetPasswordEmailAsync", ctx, user, verification)}
}

func (_c *EmailServiceMock_SendResetPasswordEmailAsync_Call) Run(run func(ctx context.Context, user *domain.User, verification *domain.Verification)) *EmailServiceMock_SendResetPasswordEmailAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 *domain.Verification
		if args[2] != nil {
			arg2 = args[2].(*domain.Verification)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmailServiceMock_SendResetPasswordEmailAsync_Call) Return() *EmailServiceMock_SendResetPasswordEmailAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *EmailServiceMock_SendResetPasswordEmailAsync_Call) RunAndReturn(run func(ctx context.Context, user *domain.User, verification *domain.Verification)) *EmailServiceMock_SendResetPasswordEmailAsync_Call {
	_c.Run(run)
	return _c
}

// SendVerifyEmailAsync provides a mock function for the type EmailServiceMock
func (_mock *EmailServiceMock) SendVerifyEmailAsync(ctx context.Context, user *domain.User, verification *domain.Verification) {
	_mock.Called(ctx, user, verification)
	return
}

// EmailServiceMock_SendVerifyEmailAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerifyEmailAsync'
type EmailServiceMock_SendVerifyEmailAsync_Call struct {
	*mock.Call
}

// SendVerifyEmailAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - verification *domain.Verification
func (_e *EmailServiceMock_Expecter) SendVerifyEmailAsync(ctx interface{}, user interface{}, verification interface{}) *EmailServiceMock_SendVerifyEmailAsync_Call {
	return &EmailServiceMock_SendVerifyEmailAsync_Call{Call: _e.mock.On("SendVerifyEmailAsync", ctx, user, verification)}
}

func (_c *EmailServiceMock_SendVerifyEmailAsync_Call) Run(run func(ctx context.Context, user *domain.User, verification *domain.Verification)) *EmailServiceMock_SendVerifyEmailAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 *domain.Verification
		if args[2] != nil {
			arg2 = args[2].(*domain.Verification)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmailServiceMock_SendVerifyEmailAsync_Call) Return() *EmailServiceMock_SendVerifyEmailAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *EmailServiceMock_SendVerifyEmailAsync_Call) RunAndReturn(run func(ctx context.Context, user *domain.User, verification *domain.Verification)) *EmailServiceMock_SendVerifyEmailAsync_Call {
	_c.Run(run)
	return _c
}

// SendWelcomeVerificationEmailAsync provides a mock function for the type EmailServiceMock
func (_mock *EmailServiceMock) SendWelcomeVerificationEmailAsync(ctx context.Context, user *domain.User, verification *domain.Verification) {
	_mock.Called(ctx, user, verification)
	return
}

// EmailServiceMock_SendWelcomeVerificationEmailAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWelcomeVerificationEmailAsync'
type EmailServiceMock_SendWelcomeVerificationEmailAsync_Call struct {
	*mock.Call
}

// SendWelcomeVerificationEmailAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - verification *domain.Verification
func (_e *EmailServiceMock_Expecter) SendWelcomeVerificationEmailAsync(ctx interface{}, user interface{}, verification interface{}) *EmailServiceMock_SendWelcomeVerificationEmailAsync_Call {
	return &EmailServiceMock_SendWelcomeVerificationEmailAsync_Call{Call: _e.mock.On("SendWelcomeVerificationEmailAsync", ctx, user, verification)}
}

func (_c *EmailServiceMock_SendWelcomeVerificationEmailAsync_Call) Run(run func(ctx context.Context, user *domain.User, verification *domain.Verification)) *EmailServiceMock_SendWelcomeVerificationEmailAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 *domain.Verification
		if args[2] != nil {
			arg2 = args[2].(*domain.Verification)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmailServiceMock_SendWelcomeVerificationEmailAsync_Call) Return() *EmailServiceMock_SendWelcomeVerificationEmailAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *EmailServiceMock_SendWelcomeVerificationEmailAsync_Call) RunAndReturn(run func(ctx context.Context, user *domain.User, verification *domain.Verification)) *EmailServiceMock_SendWelcomeVerificationEmailAsync_Call {
	_c.Run(run)
	return _c
}
