// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gbvillarinho/base-project/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewIdentityServiceMock creates a new instance of IdentityServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityServiceMock {
	mock := &IdentityServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IdentityServiceMock is an autogenerated mock type for the IdentityService type
type IdentityServiceMock struct {
	mock.Mock
}

type IdentityServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityServiceMock) EXPECT() *IdentityServiceMock_Expecter {
	return &IdentityServiceMock_Expecter{mock: &_m.Mock}
}

// ConfirmEmail provides a mock function for the type IdentityServiceMock
func (_mock *IdentityServiceMock) ConfirmEmail(ctx context.Context, token string) (*domain.ConfirmEmailResult, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmEmail")
	}

	var r0 *domain.ConfirmEmailResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.ConfirmEmailResult, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.ConfirmEmailResult); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ConfirmEmailResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityServiceMock_ConfirmEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmEmail'
type IdentityServiceMock_ConfirmEmail_Call struct {
	*mock.Call
}

// ConfirmEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *IdentityServiceMock_Expecter) ConfirmEmail(ctx interface{}, token interface{}) *IdentityServiceMock_ConfirmEmail_Call {
	return &IdentityServiceMock_ConfirmEmail_Call{Call: _e.mock.On("ConfirmEmail", ctx, token)}
}

func (_c *IdentityServiceMock_ConfirmEmail_Call) Run(run func(ctx context.Context, token string)) *IdentityServiceMock_ConfirmEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IdentityServiceMock_ConfirmEmail_Call) Return(confirmEmailResult *domain.ConfirmEmailResult, err error) *IdentityServiceMock_ConfirmEmail_Call {
	_c.Call.Return(confirmEmailResult, err)
	return _c
}

func (_c *IdentityServiceMock_ConfirmEmail_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.ConfirmEmailResult, error)) *IdentityServiceMock_ConfirmEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type IdentityServiceMock
func (_mock *IdentityServiceMock) Register(ctx context.Context, name string, email string, password string) error {
	ret := _mock.Called(ctx, name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, name, email, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IdentityServiceMock_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type IdentityServiceMock_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - password string
func (_e *IdentityServiceMock_Expecter) Register(ctx interface{}, name interface{}, email interface{}, password interface{}) *IdentityServiceMock_Register_Call {
	return &IdentityServiceMock_Register_Call{Call: _e.mock.On("Register", ctx, name, email, password)}
}

func (_c *IdentityServiceMock_Register_Call) Run(run func(ctx context.Context, name string, email string, password string)) *IdentityServiceMock_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *IdentityServiceMock_Register_Call) Return(err error) *IdentityServiceMock_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IdentityServiceMock_Register_Call) RunAndReturn(run func(ctx context.Context, name string, email string, password string) error) *IdentityServiceMock_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterMagicLink provides a mock function for the type IdentityServiceMock
func (_mock *IdentityServiceMock) RegisterMagicLink(ctx context.Context, name string, email string) error {
	ret := _mock.Called(ctx, name, email)

	if len(ret) == 0 {
		panic("no return value specified for RegisterMagicLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IdentityServiceMock_RegisterMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterMagicLink'
type IdentityServiceMock_RegisterMagicLink_Call struct {
	*mock.Call
}

// RegisterMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
func (_e *IdentityServiceMock_Expecter) RegisterMagicLink(ctx interface{}, name interface{}, email interface{}) *IdentityServiceMock_RegisterMagicLink_Call {
	return &IdentityServiceMock_RegisterMagicLink_Call{Call: _e.mock.On("RegisterMagicLink", ctx, name, email)}
}

func (_c *IdentityServiceMock_RegisterMagicLink_Call) Run(run func(ctx context.Context, name string, email string)) *IdentityServiceMock_RegisterMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IdentityServiceMock_RegisterMagicLink_Call) Return(err error) *IdentityServiceMock_RegisterMagicLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IdentityServiceMock_RegisterMagicLink_Call) RunAndReturn(run func(ctx context.Context, name string, email string) error) *IdentityServiceMock_RegisterMagicLink_Call {
	_c.Call.Return(run)
	return _c
}
