// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gbvillarinho/base-project/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewLoginServiceMock creates a new instance of LoginServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginServiceMock {
	mock := &LoginServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoginServiceMock is an autogenerated mock type for the LoginService type
type LoginServiceMock struct {
	mock.Mock
}

type LoginServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginServiceMock) EXPECT() *LoginServiceMock_Expecter {
	return &LoginServiceMock_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type LoginServiceMock
func (_mock *LoginServiceMock) Authenticate(ctx context.Context, email string, password string) (*domain.User, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoginServiceMock_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type LoginServiceMock_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *LoginServiceMock_Expecter) Authenticate(ctx interface{}, email interface{}, password interface{}) *LoginServiceMock_Authenticate_Call {
	return &LoginServiceMock_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, email, password)}
}

func (_c *LoginServiceMock_Authenticate_Call) Run(run func(ctx context.Context, email string, password string)) *LoginServiceMock_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoginServiceMock_Authenticate_Call) Return(user *domain.User, err error) *LoginServiceMock_Authenticate_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *LoginServiceMock_Authenticate_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*domain.User, error)) *LoginServiceMock_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// RequestMagicLink provides a mock function for the type LoginServiceMock
func (_mock *LoginServiceMock) RequestMagicLink(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestMagicLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoginServiceMock_RequestMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestMagicLink'
type LoginServiceMock_RequestMagicLink_Call struct {
	*mock.Call
}

// RequestMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *LoginServiceMock_Expecter) RequestMagicLink(ctx interface{}, email interface{}) *LoginServiceMock_RequestMagicLink_Call {
	return &LoginServiceMock_RequestMagicLink_Call{Call: _e.mock.On("RequestMagicLink", ctx, email)}
}

func (_c *LoginServiceMock_RequestMagicLink_Call) Run(run func(ctx context.Context, email string)) *LoginServiceMock_RequestMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoginServiceMock_RequestMagicLink_Call) Return(err error) *LoginServiceMock_RequestMagicLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoginServiceMock_RequestMagicLink_Call) RunAndReturn(run func(ctx context.Context, email string) error) *LoginServiceMock_RequestMagicLink_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyMagicLink provides a mock function for the type LoginServiceMock
func (_mock *LoginServiceMock) VerifyMagicLink(ctx context.Context, token string) (*domain.User, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyMagicLink")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoginServiceMock_VerifyMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyMagicLink'
type LoginServiceMock_VerifyMagicLink_Call struct {
	*mock.Call
}

// VerifyMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *LoginServiceMock_Expecter) VerifyMagicLink(ctx interface{}, token interface{}) *LoginServiceMock_VerifyMagicLink_Call {
	return &LoginServiceMock_VerifyMagicLink_Call{Call: _e.mock.On("VerifyMagicLink", ctx, token)}
}

func (_c *LoginServiceMock_VerifyMagicLink_Call) Run(run func(ctx context.Context, token string)) *LoginServiceMock_VerifyMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoginServiceMock_VerifyMagicLink_Call) Return(user *domain.User, err error) *LoginServiceMock_VerifyMagicLink_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *LoginServiceMock_VerifyMagicLink_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.User, error)) *LoginServiceMock_VerifyMagicLink_Call {
	_c.Call.Return(run)
	return _c
}
