// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/voxel-api/internal/infra/database/sqlc"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewQuerierMock creates a new instance of QuerierMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerierMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuerierMock {
	mock := &QuerierMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QuerierMock is an autogenerated mock type for the Querier type
type QuerierMock struct {
	mock.Mock
}

type QuerierMock_Expecter struct {
	mock *mock.Mock
}

func (_m *QuerierMock) EXPECT() *QuerierMock_Expecter {
	return &QuerierMock_Expecter{mock: &_m.Mock}
}

// BlockUser provides a mock function for the type QuerierMock
func (_mock *QuerierMock) BlockUser(ctx context.Context, arg sqlc.BlockUserParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for BlockUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.BlockUserParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_BlockUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockUser'
type QuerierMock_BlockUser_Call struct {
	*mock.Call
}

// BlockUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.BlockUserParams
func (_e *QuerierMock_Expecter) BlockUser(ctx interface{}, arg interface{}) *QuerierMock_BlockUser_Call {
	return &QuerierMock_BlockUser_Call{Call: _e.mock.On("BlockUser", ctx, arg)}
}

func (_c *QuerierMock_BlockUser_Call) Run(run func(ctx context.Context, arg sqlc.BlockUserParams)) *QuerierMock_BlockUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.BlockUserParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.BlockUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_BlockUser_Call) Return(err error) *QuerierMock_BlockUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_BlockUser_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.BlockUserParams) error) *QuerierMock_BlockUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type QuerierMock
func (_mock *QuerierMock) CreateSession(ctx context.Context, arg sqlc.CreateSessionParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateSessionParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type QuerierMock_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateSessionParams
func (_e *QuerierMock_Expecter) CreateSession(ctx interface{}, arg interface{}) *QuerierMock_CreateSession_Call {
	return &QuerierMock_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, arg)}
}

func (_c *QuerierMock_CreateSession_Call) Run(run func(ctx context.Context, arg sqlc.CreateSessionParams)) *QuerierMock_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateSessionParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_CreateSession_Call) Return(err error) *QuerierMock_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_CreateSession_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateSessionParams) error) *QuerierMock_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type QuerierMock
func (_mock *QuerierMock) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateUserParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type QuerierMock_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateUserParams
func (_e *QuerierMock_Expecter) CreateUser(ctx interface{}, arg interface{}) *QuerierMock_CreateUser_Call {
	return &QuerierMock_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *QuerierMock_CreateUser_Call) Run(run func(ctx context.Context, arg sqlc.CreateUserParams)) *QuerierMock_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_CreateUser_Call) Return(err error) *QuerierMock_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateUserParams) error) *QuerierMock_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVerification provides a mock function for the type QuerierMock
func (_mock *QuerierMock) CreateVerification(ctx context.Context, arg sqlc.CreateVerificationParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateVerificationParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_CreateVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerification'
type QuerierMock_CreateVerification_Call struct {
	*mock.Call
}

// CreateVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateVerificationParams
func (_e *QuerierMock_Expecter) CreateVerification(ctx interface{}, arg interface{}) *QuerierMock_CreateVerification_Call {
	return &QuerierMock_CreateVerification_Call{Call: _e.mock.On("CreateVerification", ctx, arg)}
}

func (_c *QuerierMock_CreateVerification_Call) Run(run func(ctx context.Context, arg sqlc.CreateVerificationParams)) *QuerierMock_CreateVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateVerificationParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateVerificationParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_CreateVerification_Call) Return(err error) *QuerierMock_CreateVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_CreateVerification_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateVerificationParams) error) *QuerierMock_CreateVerification_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionByID provides a mock function for the type QuerierMock
func (_mock *QuerierMock) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_DeleteSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionByID'
type QuerierMock_DeleteSessionByID_Call struct {
	*mock.Call
}

// DeleteSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *QuerierMock_Expecter) DeleteSessionByID(ctx interface{}, id interface{}) *QuerierMock_DeleteSessionByID_Call {
	return &QuerierMock_DeleteSessionByID_Call{Call: _e.mock.On("DeleteSessionByID", ctx, id)}
}

func (_c *QuerierMock_DeleteSessionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *QuerierMock_DeleteSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_DeleteSessionByID_Call) Return(err error) *QuerierMock_DeleteSessionByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_DeleteSessionByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *QuerierMock_DeleteSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionsByUserExceptID provides a mock function for the type QuerierMock
func (_mock *QuerierMock) DeleteSessionsByUserExceptID(ctx context.Context, arg sqlc.DeleteSessionsByUserExceptIDParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsByUserExceptID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.DeleteSessionsByUserExceptIDParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_DeleteSessionsByUserExceptID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsByUserExceptID'
type QuerierMock_DeleteSessionsByUserExceptID_Call struct {
	*mock.Call
}

// DeleteSessionsByUserExceptID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.DeleteSessionsByUserExceptIDParams
func (_e *QuerierMock_Expecter) DeleteSessionsByUserExceptID(ctx interface{}, arg interface{}) *QuerierMock_DeleteSessionsByUserExceptID_Call {
	return &QuerierMock_DeleteSessionsByUserExceptID_Call{Call: _e.mock.On("DeleteSessionsByUserExceptID", ctx, arg)}
}

func (_c *QuerierMock_DeleteSessionsByUserExceptID_Call) Run(run func(ctx context.Context, arg sqlc.DeleteSessionsByUserExceptIDParams)) *QuerierMock_DeleteSessionsByUserExceptID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.DeleteSessionsByUserExceptIDParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.DeleteSessionsByUserExceptIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_DeleteSessionsByUserExceptID_Call) Return(err error) *QuerierMock_DeleteSessionsByUserExceptID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_DeleteSessionsByUserExceptID_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.DeleteSessionsByUserExceptIDParams) error) *QuerierMock_DeleteSessionsByUserExceptID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionsByUserID provides a mock function for the type QuerierMock
func (_mock *QuerierMock) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_DeleteSessionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsByUserID'
type QuerierMock_DeleteSessionsByUserID_Call struct {
	*mock.Call
}

// DeleteSessionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *QuerierMock_Expecter) DeleteSessionsByUserID(ctx interface{}, userID interface{}) *QuerierMock_DeleteSessionsByUserID_Call {
	return &QuerierMock_DeleteSessionsByUserID_Call{Call: _e.mock.On("DeleteSessionsByUserID", ctx, userID)}
}

func (_c *QuerierMock_DeleteSessionsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *QuerierMock_DeleteSessionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_DeleteSessionsByUserID_Call) Return(err error) *QuerierMock_DeleteSessionsByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_DeleteSessionsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *QuerierMock_DeleteSessionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVerification provides a mock function for the type QuerierMock
func (_mock *QuerierMock) DeleteVerification(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_DeleteVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVerification'
type QuerierMock_DeleteVerification_Call struct {
	*mock.Call
}

// DeleteVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *QuerierMock_Expecter) DeleteVerification(ctx interface{}, id interface{}) *QuerierMock_DeleteVerification_Call {
	return &QuerierMock_DeleteVerification_Call{Call: _e.mock.On("DeleteVerification", ctx, id)}
}

func (_c *QuerierMock_DeleteVerification_Call) Run(run func(ctx context.Context, id uuid.UUID)) *QuerierMock_DeleteVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_DeleteVerification_Call) Return(err error) *QuerierMock_DeleteVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_DeleteVerification_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *QuerierMock_DeleteVerification_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVerificationsByUserIDAndFlow provides a mock function for the type QuerierMock
func (_mock *QuerierMock) DeleteVerificationsByUserIDAndFlow(ctx context.Context, arg sqlc.DeleteVerificationsByUserIDAndFlowParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVerificationsByUserIDAndFlow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.DeleteVerificationsByUserIDAndFlowParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_DeleteVerificationsByUserIDAndFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVerificationsByUserIDAndFlow'
type QuerierMock_DeleteVerificationsByUserIDAndFlow_Call struct {
	*mock.Call
}

// DeleteVerificationsByUserIDAndFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.DeleteVerificationsByUserIDAndFlowParams
func (_e *QuerierMock_Expecter) DeleteVerificationsByUserIDAndFlow(ctx interface{}, arg interface{}) *QuerierMock_DeleteVerificationsByUserIDAndFlow_Call {
	return &QuerierMock_DeleteVerificationsByUserIDAndFlow_Call{Call: _e.mock.On("DeleteVerificationsByUserIDAndFlow", ctx, arg)}
}

func (_c *QuerierMock_DeleteVerificationsByUserIDAndFlow_Call) Run(run func(ctx context.Context, arg sqlc.DeleteVerificationsByUserIDAndFlowParams)) *QuerierMock_DeleteVerificationsByUserIDAndFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.DeleteVerificationsByUserIDAndFlowParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.DeleteVerificationsByUserIDAndFlowParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_DeleteVerificationsByUserIDAndFlow_Call) Return(err error) *QuerierMock_DeleteVerificationsByUserIDAndFlow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_DeleteVerificationsByUserIDAndFlow_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.DeleteVerificationsByUserIDAndFlowParams) error) *QuerierMock_DeleteVerificationsByUserIDAndFlow_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmail provides a mock function for the type QuerierMock
func (_mock *QuerierMock) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuerierMock_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type QuerierMock_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *QuerierMock_Expecter) ExistsByEmail(ctx interface{}, email interface{}) *QuerierMock_ExistsByEmail_Call {
	return &QuerierMock_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", ctx, email)}
}

func (_c *QuerierMock_ExistsByEmail_Call) Run(run func(ctx context.Context, email string)) *QuerierMock_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_ExistsByEmail_Call) Return(b bool, err error) *QuerierMock_ExistsByEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *QuerierMock_ExistsByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *QuerierMock_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessionByID provides a mock function for the type QuerierMock
func (_mock *QuerierMock) FindSessionByID(ctx context.Context, id uuid.UUID) (sqlc.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindSessionByID")
	}

	var r0 sqlc.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuerierMock_FindSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessionByID'
type QuerierMock_FindSessionByID_Call struct {
	*mock.Call
}

// FindSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *QuerierMock_Expecter) FindSessionByID(ctx interface{}, id interface{}) *QuerierMock_FindSessionByID_Call {
	return &QuerierMock_FindSessionByID_Call{Call: _e.mock.On("FindSessionByID", ctx, id)}
}

func (_c *QuerierMock_FindSessionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *QuerierMock_FindSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_FindSessionByID_Call) Return(session sqlc.Session, err error) *QuerierMock_FindSessionByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *QuerierMock_FindSessionByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.Session, error)) *QuerierMock_FindSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessionByToken provides a mock function for the type QuerierMock
func (_mock *QuerierMock) FindSessionByToken(ctx context.Context, token string) (sqlc.Session, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindSessionByToken")
	}

	var r0 sqlc.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.Session, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.Session); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(sqlc.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuerierMock_FindSessionByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessionByToken'
type QuerierMock_FindSessionByToken_Call struct {
	*mock.Call
}

// FindSessionByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *QuerierMock_Expecter) FindSessionByToken(ctx interface{}, token interface{}) *QuerierMock_FindSessionByToken_Call {
	return &QuerierMock_FindSessionByToken_Call{Call: _e.mock.On("FindSessionByToken", ctx, token)}
}

func (_c *QuerierMock_FindSessionByToken_Call) Run(run func(ctx context.Context, token string)) *QuerierMock_FindSessionByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_FindSessionByToken_Call) Return(session sqlc.Session, err error) *QuerierMock_FindSessionByToken_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *QuerierMock_FindSessionByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (sqlc.Session, error)) *QuerierMock_FindSessionByToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessionsByUserID provides a mock function for the type QuerierMock
func (_mock *QuerierMock) FindSessionsByUserID(ctx context.Context, arg sqlc.FindSessionsByUserIDParams) ([]sqlc.Session, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindSessionsByUserID")
	}

	var r0 []sqlc.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindSessionsByUserIDParams) ([]sqlc.Session, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindSessionsByUserIDParams) []sqlc.Session); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindSessionsByUserIDParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuerierMock_FindSessionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessionsByUserID'
type QuerierMock_FindSessionsByUserID_Call struct {
	*mock.Call
}

// FindSessionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.FindSessionsByUserIDParams
func (_e *QuerierMock_Expecter) FindSessionsByUserID(ctx interface{}, arg interface{}) *QuerierMock_FindSessionsByUserID_Call {
	return &QuerierMock_FindSessionsByUserID_Call{Call: _e.mock.On("FindSessionsByUserID", ctx, arg)}
}

func (_c *QuerierMock_FindSessionsByUserID_Call) Run(run func(ctx context.Context, arg sqlc.FindSessionsByUserIDParams)) *QuerierMock_FindSessionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindSessionsByUserIDParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindSessionsByUserIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_FindSessionsByUserID_Call) Return(sessions []sqlc.Session, err error) *QuerierMock_FindSessionsByUserID_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *QuerierMock_FindSessionsByUserID_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.FindSessionsByUserIDParams) ([]sqlc.Session, error)) *QuerierMock_FindSessionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type QuerierMock
func (_mock *QuerierMock) FindUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 sqlc.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuerierMock_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type QuerierMock_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *QuerierMock_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *QuerierMock_FindUserByEmail_Call {
	return &QuerierMock_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *QuerierMock_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *QuerierMock_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_FindUserByEmail_Call) Return(user sqlc.User, err error) *QuerierMock_FindUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *QuerierMock_FindUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (sqlc.User, error)) *QuerierMock_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function for the type QuerierMock
func (_mock *QuerierMock) FindUserByID(ctx context.Context, id uuid.UUID) (sqlc.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 sqlc.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuerierMock_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type QuerierMock_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *QuerierMock_Expecter) FindUserByID(ctx interface{}, id interface{}) *QuerierMock_FindUserByID_Call {
	return &QuerierMock_FindUserByID_Call{Call: _e.mock.On("FindUserByID", ctx, id)}
}

func (_c *QuerierMock_FindUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *QuerierMock_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_FindUserByID_Call) Return(user sqlc.User, err error) *QuerierMock_FindUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *QuerierMock_FindUserByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.User, error)) *QuerierMock_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindValidVerificationByUserIDAndFlow provides a mock function for the type QuerierMock
func (_mock *QuerierMock) FindValidVerificationByUserIDAndFlow(ctx context.Context, arg sqlc.FindValidVerificationByUserIDAndFlowParams) (sqlc.Verification, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindValidVerificationByUserIDAndFlow")
	}

	var r0 sqlc.Verification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindValidVerificationByUserIDAndFlowParams) (sqlc.Verification, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindValidVerificationByUserIDAndFlowParams) sqlc.Verification); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Verification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindValidVerificationByUserIDAndFlowParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuerierMock_FindValidVerificationByUserIDAndFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindValidVerificationByUserIDAndFlow'
type QuerierMock_FindValidVerificationByUserIDAndFlow_Call struct {
	*mock.Call
}

// FindValidVerificationByUserIDAndFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.FindValidVerificationByUserIDAndFlowParams
func (_e *QuerierMock_Expecter) FindValidVerificationByUserIDAndFlow(ctx interface{}, arg interface{}) *QuerierMock_FindValidVerificationByUserIDAndFlow_Call {
	return &QuerierMock_FindValidVerificationByUserIDAndFlow_Call{Call: _e.mock.On("FindValidVerificationByUserIDAndFlow", ctx, arg)}
}

func (_c *QuerierMock_FindValidVerificationByUserIDAndFlow_Call) Run(run func(ctx context.Context, arg sqlc.FindValidVerificationByUserIDAndFlowParams)) *QuerierMock_FindValidVerificationByUserIDAndFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindValidVerificationByUserIDAndFlowParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindValidVerificationByUserIDAndFlowParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_FindValidVerificationByUserIDAndFlow_Call) Return(verification sqlc.Verification, err error) *QuerierMock_FindValidVerificationByUserIDAndFlow_Call {
	_c.Call.Return(verification, err)
	return _c
}

func (_c *QuerierMock_FindValidVerificationByUserIDAndFlow_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.FindValidVerificationByUserIDAndFlowParams) (sqlc.Verification, error)) *QuerierMock_FindValidVerificationByUserIDAndFlow_Call {
	_c.Call.Return(run)
	return _c
}

// FindVerificationByID provides a mock function for the type QuerierMock
func (_mock *QuerierMock) FindVerificationByID(ctx context.Context, id uuid.UUID) (sqlc.Verification, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindVerificationByID")
	}

	var r0 sqlc.Verification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.Verification, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.Verification); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Verification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuerierMock_FindVerificationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVerificationByID'
type QuerierMock_FindVerificationByID_Call struct {
	*mock.Call
}

// FindVerificationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *QuerierMock_Expecter) FindVerificationByID(ctx interface{}, id interface{}) *QuerierMock_FindVerificationByID_Call {
	return &QuerierMock_FindVerificationByID_Call{Call: _e.mock.On("FindVerificationByID", ctx, id)}
}

func (_c *QuerierMock_FindVerificationByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *QuerierMock_FindVerificationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_FindVerificationByID_Call) Return(verification sqlc.Verification, err error) *QuerierMock_FindVerificationByID_Call {
	_c.Call.Return(verification, err)
	return _c
}

func (_c *QuerierMock_FindVerificationByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.Verification, error)) *QuerierMock_FindVerificationByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindVerificationByToken provides a mock function for the type QuerierMock
func (_mock *QuerierMock) FindVerificationByToken(ctx context.Context, token string) (sqlc.Verification, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindVerificationByToken")
	}

	var r0 sqlc.Verification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.Verification, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.Verification); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(sqlc.Verification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuerierMock_FindVerificationByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVerificationByToken'
type QuerierMock_FindVerificationByToken_Call struct {
	*mock.Call
}

// FindVerificationByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *QuerierMock_Expecter) FindVerificationByToken(ctx interface{}, token interface{}) *QuerierMock_FindVerificationByToken_Call {
	return &QuerierMock_FindVerificationByToken_Call{Call: _e.mock.On("FindVerificationByToken", ctx, token)}
}

func (_c *QuerierMock_FindVerificationByToken_Call) Run(run func(ctx context.Context, token string)) *QuerierMock_FindVerificationByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_FindVerificationByToken_Call) Return(verification sqlc.Verification, err error) *QuerierMock_FindVerificationByToken_Call {
	_c.Call.Return(verification, err)
	return _c
}

func (_c *QuerierMock_FindVerificationByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (sqlc.Verification, error)) *QuerierMock_FindVerificationByToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserEmail provides a mock function for the type QuerierMock
func (_mock *QuerierMock) UpdateUserEmail(ctx context.Context, arg sqlc.UpdateUserEmailParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserEmailParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_UpdateUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserEmail'
type QuerierMock_UpdateUserEmail_Call struct {
	*mock.Call
}

// UpdateUserEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateUserEmailParams
func (_e *QuerierMock_Expecter) UpdateUserEmail(ctx interface{}, arg interface{}) *QuerierMock_UpdateUserEmail_Call {
	return &QuerierMock_UpdateUserEmail_Call{Call: _e.mock.On("UpdateUserEmail", ctx, arg)}
}

func (_c *QuerierMock_UpdateUserEmail_Call) Run(run func(ctx context.Context, arg sqlc.UpdateUserEmailParams)) *QuerierMock_UpdateUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateUserEmailParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateUserEmailParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_UpdateUserEmail_Call) Return(err error) *QuerierMock_UpdateUserEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_UpdateUserEmail_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateUserEmailParams) error) *QuerierMock_UpdateUserEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserName provides a mock function for the type QuerierMock
func (_mock *QuerierMock) UpdateUserName(ctx context.Context, arg sqlc.UpdateUserNameParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserNameParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_UpdateUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserName'
type QuerierMock_UpdateUserName_Call struct {
	*mock.Call
}

// UpdateUserName is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateUserNameParams
func (_e *QuerierMock_Expecter) UpdateUserName(ctx interface{}, arg interface{}) *QuerierMock_UpdateUserName_Call {
	return &QuerierMock_UpdateUserName_Call{Call: _e.mock.On("UpdateUserName", ctx, arg)}
}

func (_c *QuerierMock_UpdateUserName_Call) Run(run func(ctx context.Context, arg sqlc.UpdateUserNameParams)) *QuerierMock_UpdateUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateUserNameParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateUserNameParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_UpdateUserName_Call) Return(err error) *QuerierMock_UpdateUserName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_UpdateUserName_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateUserNameParams) error) *QuerierMock_UpdateUserName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function for the type QuerierMock
func (_mock *QuerierMock) UpdateUserPassword(ctx context.Context, arg sqlc.UpdateUserPasswordParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserPasswordParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type QuerierMock_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateUserPasswordParams
func (_e *QuerierMock_Expecter) UpdateUserPassword(ctx interface{}, arg interface{}) *QuerierMock_UpdateUserPassword_Call {
	return &QuerierMock_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, arg)}
}

func (_c *QuerierMock_UpdateUserPassword_Call) Run(run func(ctx context.Context, arg sqlc.UpdateUserPasswordParams)) *QuerierMock_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateUserPasswordParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateUserPasswordParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_UpdateUserPassword_Call) Return(err error) *QuerierMock_UpdateUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_UpdateUserPassword_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateUserPasswordParams) error) *QuerierMock_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyUserEmail provides a mock function for the type QuerierMock
func (_mock *QuerierMock) VerifyUserEmail(ctx context.Context, arg sqlc.VerifyUserEmailParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for VerifyUserEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.VerifyUserEmailParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuerierMock_VerifyUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyUserEmail'
type QuerierMock_VerifyUserEmail_Call struct {
	*mock.Call
}

// VerifyUserEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.VerifyUserEmailParams
func (_e *QuerierMock_Expecter) VerifyUserEmail(ctx interface{}, arg interface{}) *QuerierMock_VerifyUserEmail_Call {
	return &QuerierMock_VerifyUserEmail_Call{Call: _e.mock.On("VerifyUserEmail", ctx, arg)}
}

func (_c *QuerierMock_VerifyUserEmail_Call) Run(run func(ctx context.Context, arg sqlc.VerifyUserEmailParams)) *QuerierMock_VerifyUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.VerifyUserEmailParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.VerifyUserEmailParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuerierMock_VerifyUserEmail_Call) Return(err error) *QuerierMock_VerifyUserEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuerierMock_VerifyUserEmail_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.VerifyUserEmailParams) error) *QuerierMock_VerifyUserEmail_Call {
	_c.Call.Return(run)
	return _c
}
