// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gbvillarinho/base-project/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSecurityServiceMock creates a new instance of SecurityServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecurityServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecurityServiceMock {
	mock := &SecurityServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecurityServiceMock is an autogenerated mock type for the SecurityService type
type SecurityServiceMock struct {
	mock.Mock
}

type SecurityServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SecurityServiceMock) EXPECT() *SecurityServiceMock_Expecter {
	return &SecurityServiceMock_Expecter{mock: &_m.Mock}
}

// ChangeEmail provides a mock function for the type SecurityServiceMock
func (_mock *SecurityServiceMock) ChangeEmail(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ChangeEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecurityServiceMock_ChangeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeEmail'
type SecurityServiceMock_ChangeEmail_Call struct {
	*mock.Call
}

// ChangeEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *SecurityServiceMock_Expecter) ChangeEmail(ctx interface{}, token interface{}) *SecurityServiceMock_ChangeEmail_Call {
	return &SecurityServiceMock_ChangeEmail_Call{Call: _e.mock.On("ChangeEmail", ctx, token)}
}

func (_c *SecurityServiceMock_ChangeEmail_Call) Run(run func(ctx context.Context, token string)) *SecurityServiceMock_ChangeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecurityServiceMock_ChangeEmail_Call) Return(err error) *SecurityServiceMock_ChangeEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecurityServiceMock_ChangeEmail_Call) RunAndReturn(run func(ctx context.Context, token string) error) *SecurityServiceMock_ChangeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type SecurityServiceMock
func (_mock *SecurityServiceMock) ResetPassword(ctx context.Context, token string, newPassword string) (*domain.ResetPasswordResult, error) {
	ret := _mock.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 *domain.ResetPasswordResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.ResetPasswordResult, error)); ok {
		return returnFunc(ctx, token, newPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.ResetPasswordResult); ok {
		r0 = returnFunc(ctx, token, newPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ResetPasswordResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, token, newPassword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecurityServiceMock_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type SecurityServiceMock_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - newPassword string
func (_e *SecurityServiceMock_Expecter) ResetPassword(ctx interface{}, token interface{}, newPassword interface{}) *SecurityServiceMock_ResetPassword_Call {
	return &SecurityServiceMock_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, token, newPassword)}
}

func (_c *SecurityServiceMock_ResetPassword_Call) Run(run func(ctx context.Context, token string, newPassword string)) *SecurityServiceMock_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SecurityServiceMock_ResetPassword_Call) Return(resetPasswordResult *domain.ResetPasswordResult, err error) *SecurityServiceMock_ResetPassword_Call {
	_c.Call.Return(resetPasswordResult, err)
	return _c
}

func (_c *SecurityServiceMock_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, token string, newPassword string) (*domain.ResetPasswordResult, error)) *SecurityServiceMock_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// StartChangeEmail provides a mock function for the type SecurityServiceMock
func (_mock *SecurityServiceMock) StartChangeEmail(ctx context.Context, userID uuid.UUID, newEmail string) error {
	ret := _mock.Called(ctx, userID, newEmail)

	if len(ret) == 0 {
		panic("no return value specified for StartChangeEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, newEmail)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecurityServiceMock_StartChangeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartChangeEmail'
type SecurityServiceMock_StartChangeEmail_Call struct {
	*mock.Call
}

// StartChangeEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - newEmail string
func (_e *SecurityServiceMock_Expecter) StartChangeEmail(ctx interface{}, userID interface{}, newEmail interface{}) *SecurityServiceMock_StartChangeEmail_Call {
	return &SecurityServiceMock_StartChangeEmail_Call{Call: _e.mock.On("StartChangeEmail", ctx, userID, newEmail)}
}

func (_c *SecurityServiceMock_StartChangeEmail_Call) Run(run func(ctx context.Context, userID uuid.UUID, newEmail string)) *SecurityServiceMock_StartChangeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SecurityServiceMock_StartChangeEmail_Call) Return(err error) *SecurityServiceMock_StartChangeEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecurityServiceMock_StartChangeEmail_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, newEmail string) error) *SecurityServiceMock_StartChangeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// StartPasswordReset provides a mock function for the type SecurityServiceMock
func (_mock *SecurityServiceMock) StartPasswordReset(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for StartPasswordReset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecurityServiceMock_StartPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartPasswordReset'
type SecurityServiceMock_StartPasswordReset_Call struct {
	*mock.Call
}

// StartPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *SecurityServiceMock_Expecter) StartPasswordReset(ctx interface{}, email interface{}) *SecurityServiceMock_StartPasswordReset_Call {
	return &SecurityServiceMock_StartPasswordReset_Call{Call: _e.mock.On("StartPasswordReset", ctx, email)}
}

func (_c *SecurityServiceMock_StartPasswordReset_Call) Run(run func(ctx context.Context, email string)) *SecurityServiceMock_StartPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecurityServiceMock_StartPasswordReset_Call) Return(err error) *SecurityServiceMock_StartPasswordReset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecurityServiceMock_StartPasswordReset_Call) RunAndReturn(run func(ctx context.Context, email string) error) *SecurityServiceMock_StartPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type SecurityServiceMock
func (_mock *SecurityServiceMock) UpdatePassword(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string) error {
	ret := _mock.Called(ctx, userID, currentPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, userID, currentPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecurityServiceMock_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type SecurityServiceMock_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currentPassword string
//   - newPassword string
func (_e *SecurityServiceMock_Expecter) UpdatePassword(ctx interface{}, userID interface{}, currentPassword interface{}, newPassword interface{}) *SecurityServiceMock_UpdatePassword_Call {
	return &SecurityServiceMock_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, currentPassword, newPassword)}
}

func (_c *SecurityServiceMock_UpdatePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string)) *SecurityServiceMock_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SecurityServiceMock_UpdatePassword_Call) Return(err error) *SecurityServiceMock_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecurityServiceMock_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string) error) *SecurityServiceMock_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}
