// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/voxel-api/internal/infra/database/sqlc"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewStoreMock creates a new instance of StoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreMock {
	mock := &StoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StoreMock is an autogenerated mock type for the Store type
type StoreMock struct {
	mock.Mock
}

type StoreMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StoreMock) EXPECT() *StoreMock_Expecter {
	return &StoreMock_Expecter{mock: &_m.Mock}
}

// BlockUser provides a mock function for the type StoreMock
func (_mock *StoreMock) BlockUser(ctx context.Context, arg sqlc.BlockUserParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for BlockUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.BlockUserParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_BlockUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockUser'
type StoreMock_BlockUser_Call struct {
	*mock.Call
}

// BlockUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.BlockUserParams
func (_e *StoreMock_Expecter) BlockUser(ctx interface{}, arg interface{}) *StoreMock_BlockUser_Call {
	return &StoreMock_BlockUser_Call{Call: _e.mock.On("BlockUser", ctx, arg)}
}

func (_c *StoreMock_BlockUser_Call) Run(run func(ctx context.Context, arg sqlc.BlockUserParams)) *StoreMock_BlockUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.BlockUserParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.BlockUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_BlockUser_Call) Return(err error) *StoreMock_BlockUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_BlockUser_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.BlockUserParams) error) *StoreMock_BlockUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type StoreMock
func (_mock *StoreMock) CreateSession(ctx context.Context, arg sqlc.CreateSessionParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateSessionParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type StoreMock_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateSessionParams
func (_e *StoreMock_Expecter) CreateSession(ctx interface{}, arg interface{}) *StoreMock_CreateSession_Call {
	return &StoreMock_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, arg)}
}

func (_c *StoreMock_CreateSession_Call) Run(run func(ctx context.Context, arg sqlc.CreateSessionParams)) *StoreMock_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateSessionParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_CreateSession_Call) Return(err error) *StoreMock_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_CreateSession_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateSessionParams) error) *StoreMock_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type StoreMock
func (_mock *StoreMock) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateUserParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type StoreMock_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateUserParams
func (_e *StoreMock_Expecter) CreateUser(ctx interface{}, arg interface{}) *StoreMock_CreateUser_Call {
	return &StoreMock_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *StoreMock_CreateUser_Call) Run(run func(ctx context.Context, arg sqlc.CreateUserParams)) *StoreMock_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_CreateUser_Call) Return(err error) *StoreMock_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateUserParams) error) *StoreMock_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVerification provides a mock function for the type StoreMock
func (_mock *StoreMock) CreateVerification(ctx context.Context, arg sqlc.CreateVerificationParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateVerificationParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_CreateVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerification'
type StoreMock_CreateVerification_Call struct {
	*mock.Call
}

// CreateVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateVerificationParams
func (_e *StoreMock_Expecter) CreateVerification(ctx interface{}, arg interface{}) *StoreMock_CreateVerification_Call {
	return &StoreMock_CreateVerification_Call{Call: _e.mock.On("CreateVerification", ctx, arg)}
}

func (_c *StoreMock_CreateVerification_Call) Run(run func(ctx context.Context, arg sqlc.CreateVerificationParams)) *StoreMock_CreateVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateVerificationParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateVerificationParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_CreateVerification_Call) Return(err error) *StoreMock_CreateVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_CreateVerification_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateVerificationParams) error) *StoreMock_CreateVerification_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionByID provides a mock function for the type StoreMock
func (_mock *StoreMock) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_DeleteSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionByID'
type StoreMock_DeleteSessionByID_Call struct {
	*mock.Call
}

// DeleteSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *StoreMock_Expecter) DeleteSessionByID(ctx interface{}, id interface{}) *StoreMock_DeleteSessionByID_Call {
	return &StoreMock_DeleteSessionByID_Call{Call: _e.mock.On("DeleteSessionByID", ctx, id)}
}

func (_c *StoreMock_DeleteSessionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *StoreMock_DeleteSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_DeleteSessionByID_Call) Return(err error) *StoreMock_DeleteSessionByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_DeleteSessionByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *StoreMock_DeleteSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionsByUserExceptID provides a mock function for the type StoreMock
func (_mock *StoreMock) DeleteSessionsByUserExceptID(ctx context.Context, arg sqlc.DeleteSessionsByUserExceptIDParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsByUserExceptID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.DeleteSessionsByUserExceptIDParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_DeleteSessionsByUserExceptID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsByUserExceptID'
type StoreMock_DeleteSessionsByUserExceptID_Call struct {
	*mock.Call
}

// DeleteSessionsByUserExceptID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.DeleteSessionsByUserExceptIDParams
func (_e *StoreMock_Expecter) DeleteSessionsByUserExceptID(ctx interface{}, arg interface{}) *StoreMock_DeleteSessionsByUserExceptID_Call {
	return &StoreMock_DeleteSessionsByUserExceptID_Call{Call: _e.mock.On("DeleteSessionsByUserExceptID", ctx, arg)}
}

func (_c *StoreMock_DeleteSessionsByUserExceptID_Call) Run(run func(ctx context.Context, arg sqlc.DeleteSessionsByUserExceptIDParams)) *StoreMock_DeleteSessionsByUserExceptID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.DeleteSessionsByUserExceptIDParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.DeleteSessionsByUserExceptIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_DeleteSessionsByUserExceptID_Call) Return(err error) *StoreMock_DeleteSessionsByUserExceptID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_DeleteSessionsByUserExceptID_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.DeleteSessionsByUserExceptIDParams) error) *StoreMock_DeleteSessionsByUserExceptID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionsByUserID provides a mock function for the type StoreMock
func (_mock *StoreMock) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_DeleteSessionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsByUserID'
type StoreMock_DeleteSessionsByUserID_Call struct {
	*mock.Call
}

// DeleteSessionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *StoreMock_Expecter) DeleteSessionsByUserID(ctx interface{}, userID interface{}) *StoreMock_DeleteSessionsByUserID_Call {
	return &StoreMock_DeleteSessionsByUserID_Call{Call: _e.mock.On("DeleteSessionsByUserID", ctx, userID)}
}

func (_c *StoreMock_DeleteSessionsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *StoreMock_DeleteSessionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_DeleteSessionsByUserID_Call) Return(err error) *StoreMock_DeleteSessionsByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_DeleteSessionsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *StoreMock_DeleteSessionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVerification provides a mock function for the type StoreMock
func (_mock *StoreMock) DeleteVerification(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_DeleteVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVerification'
type StoreMock_DeleteVerification_Call struct {
	*mock.Call
}

// DeleteVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *StoreMock_Expecter) DeleteVerification(ctx interface{}, id interface{}) *StoreMock_DeleteVerification_Call {
	return &StoreMock_DeleteVerification_Call{Call: _e.mock.On("DeleteVerification", ctx, id)}
}

func (_c *StoreMock_DeleteVerification_Call) Run(run func(ctx context.Context, id uuid.UUID)) *StoreMock_DeleteVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_DeleteVerification_Call) Return(err error) *StoreMock_DeleteVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_DeleteVerification_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *StoreMock_DeleteVerification_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVerificationsByUserIDAndFlow provides a mock function for the type StoreMock
func (_mock *StoreMock) DeleteVerificationsByUserIDAndFlow(ctx context.Context, arg sqlc.DeleteVerificationsByUserIDAndFlowParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVerificationsByUserIDAndFlow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.DeleteVerificationsByUserIDAndFlowParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_DeleteVerificationsByUserIDAndFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVerificationsByUserIDAndFlow'
type StoreMock_DeleteVerificationsByUserIDAndFlow_Call struct {
	*mock.Call
}

// DeleteVerificationsByUserIDAndFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.DeleteVerificationsByUserIDAndFlowParams
func (_e *StoreMock_Expecter) DeleteVerificationsByUserIDAndFlow(ctx interface{}, arg interface{}) *StoreMock_DeleteVerificationsByUserIDAndFlow_Call {
	return &StoreMock_DeleteVerificationsByUserIDAndFlow_Call{Call: _e.mock.On("DeleteVerificationsByUserIDAndFlow", ctx, arg)}
}

func (_c *StoreMock_DeleteVerificationsByUserIDAndFlow_Call) Run(run func(ctx context.Context, arg sqlc.DeleteVerificationsByUserIDAndFlowParams)) *StoreMock_DeleteVerificationsByUserIDAndFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.DeleteVerificationsByUserIDAndFlowParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.DeleteVerificationsByUserIDAndFlowParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_DeleteVerificationsByUserIDAndFlow_Call) Return(err error) *StoreMock_DeleteVerificationsByUserIDAndFlow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_DeleteVerificationsByUserIDAndFlow_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.DeleteVerificationsByUserIDAndFlowParams) error) *StoreMock_DeleteVerificationsByUserIDAndFlow_Call {
	_c.Call.Return(run)
	return _c
}

// ExecTx provides a mock function for the type StoreMock
func (_mock *StoreMock) ExecTx(ctx context.Context, fn func(sqlc.Querier) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(sqlc.Querier) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_ExecTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecTx'
type StoreMock_ExecTx_Call struct {
	*mock.Call
}

// ExecTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(sqlc.Querier) error
func (_e *StoreMock_Expecter) ExecTx(ctx interface{}, fn interface{}) *StoreMock_ExecTx_Call {
	return &StoreMock_ExecTx_Call{Call: _e.mock.On("ExecTx", ctx, fn)}
}

func (_c *StoreMock_ExecTx_Call) Run(run func(ctx context.Context, fn func(sqlc.Querier) error)) *StoreMock_ExecTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(sqlc.Querier) error
		if args[1] != nil {
			arg1 = args[1].(func(sqlc.Querier) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_ExecTx_Call) Return(err error) *StoreMock_ExecTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_ExecTx_Call) RunAndReturn(run func(ctx context.Context, fn func(sqlc.Querier) error) error) *StoreMock_ExecTx_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmail provides a mock function for the type StoreMock
func (_mock *StoreMock) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type StoreMock_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *StoreMock_Expecter) ExistsByEmail(ctx interface{}, email interface{}) *StoreMock_ExistsByEmail_Call {
	return &StoreMock_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", ctx, email)}
}

func (_c *StoreMock_ExistsByEmail_Call) Run(run func(ctx context.Context, email string)) *StoreMock_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_ExistsByEmail_Call) Return(b bool, err error) *StoreMock_ExistsByEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *StoreMock_ExistsByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *StoreMock_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessionByID provides a mock function for the type StoreMock
func (_mock *StoreMock) FindSessionByID(ctx context.Context, id uuid.UUID) (sqlc.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindSessionByID")
	}

	var r0 sqlc.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_FindSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessionByID'
type StoreMock_FindSessionByID_Call struct {
	*mock.Call
}

// FindSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *StoreMock_Expecter) FindSessionByID(ctx interface{}, id interface{}) *StoreMock_FindSessionByID_Call {
	return &StoreMock_FindSessionByID_Call{Call: _e.mock.On("FindSessionByID", ctx, id)}
}

func (_c *StoreMock_FindSessionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *StoreMock_FindSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_FindSessionByID_Call) Return(session sqlc.Session, err error) *StoreMock_FindSessionByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *StoreMock_FindSessionByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.Session, error)) *StoreMock_FindSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessionByToken provides a mock function for the type StoreMock
func (_mock *StoreMock) FindSessionByToken(ctx context.Context, token string) (sqlc.Session, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindSessionByToken")
	}

	var r0 sqlc.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.Session, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.Session); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(sqlc.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_FindSessionByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessionByToken'
type StoreMock_FindSessionByToken_Call struct {
	*mock.Call
}

// FindSessionByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *StoreMock_Expecter) FindSessionByToken(ctx interface{}, token interface{}) *StoreMock_FindSessionByToken_Call {
	return &StoreMock_FindSessionByToken_Call{Call: _e.mock.On("FindSessionByToken", ctx, token)}
}

func (_c *StoreMock_FindSessionByToken_Call) Run(run func(ctx context.Context, token string)) *StoreMock_FindSessionByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_FindSessionByToken_Call) Return(session sqlc.Session, err error) *StoreMock_FindSessionByToken_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *StoreMock_FindSessionByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (sqlc.Session, error)) *StoreMock_FindSessionByToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessionsByUserID provides a mock function for the type StoreMock
func (_mock *StoreMock) FindSessionsByUserID(ctx context.Context, arg sqlc.FindSessionsByUserIDParams) ([]sqlc.Session, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindSessionsByUserID")
	}

	var r0 []sqlc.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindSessionsByUserIDParams) ([]sqlc.Session, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindSessionsByUserIDParams) []sqlc.Session); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindSessionsByUserIDParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_FindSessionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessionsByUserID'
type StoreMock_FindSessionsByUserID_Call struct {
	*mock.Call
}

// FindSessionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.FindSessionsByUserIDParams
func (_e *StoreMock_Expecter) FindSessionsByUserID(ctx interface{}, arg interface{}) *StoreMock_FindSessionsByUserID_Call {
	return &StoreMock_FindSessionsByUserID_Call{Call: _e.mock.On("FindSessionsByUserID", ctx, arg)}
}

func (_c *StoreMock_FindSessionsByUserID_Call) Run(run func(ctx context.Context, arg sqlc.FindSessionsByUserIDParams)) *StoreMock_FindSessionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindSessionsByUserIDParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindSessionsByUserIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_FindSessionsByUserID_Call) Return(sessions []sqlc.Session, err error) *StoreMock_FindSessionsByUserID_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *StoreMock_FindSessionsByUserID_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.FindSessionsByUserIDParams) ([]sqlc.Session, error)) *StoreMock_FindSessionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type StoreMock
func (_mock *StoreMock) FindUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 sqlc.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type StoreMock_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *StoreMock_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *StoreMock_FindUserByEmail_Call {
	return &StoreMock_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *StoreMock_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *StoreMock_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_FindUserByEmail_Call) Return(user sqlc.User, err error) *StoreMock_FindUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *StoreMock_FindUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (sqlc.User, error)) *StoreMock_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function for the type StoreMock
func (_mock *StoreMock) FindUserByID(ctx context.Context, id uuid.UUID) (sqlc.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 sqlc.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type StoreMock_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *StoreMock_Expecter) FindUserByID(ctx interface{}, id interface{}) *StoreMock_FindUserByID_Call {
	return &StoreMock_FindUserByID_Call{Call: _e.mock.On("FindUserByID", ctx, id)}
}

func (_c *StoreMock_FindUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *StoreMock_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_FindUserByID_Call) Return(user sqlc.User, err error) *StoreMock_FindUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *StoreMock_FindUserByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.User, error)) *StoreMock_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindValidVerificationByUserIDAndFlow provides a mock function for the type StoreMock
func (_mock *StoreMock) FindValidVerificationByUserIDAndFlow(ctx context.Context, arg sqlc.FindValidVerificationByUserIDAndFlowParams) (sqlc.Verification, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindValidVerificationByUserIDAndFlow")
	}

	var r0 sqlc.Verification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindValidVerificationByUserIDAndFlowParams) (sqlc.Verification, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindValidVerificationByUserIDAndFlowParams) sqlc.Verification); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Verification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindValidVerificationByUserIDAndFlowParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_FindValidVerificationByUserIDAndFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindValidVerificationByUserIDAndFlow'
type StoreMock_FindValidVerificationByUserIDAndFlow_Call struct {
	*mock.Call
}

// FindValidVerificationByUserIDAndFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.FindValidVerificationByUserIDAndFlowParams
func (_e *StoreMock_Expecter) FindValidVerificationByUserIDAndFlow(ctx interface{}, arg interface{}) *StoreMock_FindValidVerificationByUserIDAndFlow_Call {
	return &StoreMock_FindValidVerificationByUserIDAndFlow_Call{Call: _e.mock.On("FindValidVerificationByUserIDAndFlow", ctx, arg)}
}

func (_c *StoreMock_FindValidVerificationByUserIDAndFlow_Call) Run(run func(ctx context.Context, arg sqlc.FindValidVerificationByUserIDAndFlowParams)) *StoreMock_FindValidVerificationByUserIDAndFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindValidVerificationByUserIDAndFlowParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindValidVerificationByUserIDAndFlowParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_FindValidVerificationByUserIDAndFlow_Call) Return(verification sqlc.Verification, err error) *StoreMock_FindValidVerificationByUserIDAndFlow_Call {
	_c.Call.Return(verification, err)
	return _c
}

func (_c *StoreMock_FindValidVerificationByUserIDAndFlow_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.FindValidVerificationByUserIDAndFlowParams) (sqlc.Verification, error)) *StoreMock_FindValidVerificationByUserIDAndFlow_Call {
	_c.Call.Return(run)
	return _c
}

// FindVerificationByID provides a mock function for the type StoreMock
func (_mock *StoreMock) FindVerificationByID(ctx context.Context, id uuid.UUID) (sqlc.Verification, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindVerificationByID")
	}

	var r0 sqlc.Verification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.Verification, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.Verification); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Verification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_FindVerificationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVerificationByID'
type StoreMock_FindVerificationByID_Call struct {
	*mock.Call
}

// FindVerificationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *StoreMock_Expecter) FindVerificationByID(ctx interface{}, id interface{}) *StoreMock_FindVerificationByID_Call {
	return &StoreMock_FindVerificationByID_Call{Call: _e.mock.On("FindVerificationByID", ctx, id)}
}

func (_c *StoreMock_FindVerificationByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *StoreMock_FindVerificationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_FindVerificationByID_Call) Return(verification sqlc.Verification, err error) *StoreMock_FindVerificationByID_Call {
	_c.Call.Return(verification, err)
	return _c
}

func (_c *StoreMock_FindVerificationByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.Verification, error)) *StoreMock_FindVerificationByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindVerificationByToken provides a mock function for the type StoreMock
func (_mock *StoreMock) FindVerificationByToken(ctx context.Context, token string) (sqlc.Verification, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindVerificationByToken")
	}

	var r0 sqlc.Verification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.Verification, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.Verification); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(sqlc.Verification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_FindVerificationByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVerificationByToken'
type StoreMock_FindVerificationByToken_Call struct {
	*mock.Call
}

// FindVerificationByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *StoreMock_Expecter) FindVerificationByToken(ctx interface{}, token interface{}) *StoreMock_FindVerificationByToken_Call {
	return &StoreMock_FindVerificationByToken_Call{Call: _e.mock.On("FindVerificationByToken", ctx, token)}
}

func (_c *StoreMock_FindVerificationByToken_Call) Run(run func(ctx context.Context, token string)) *StoreMock_FindVerificationByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_FindVerificationByToken_Call) Return(verification sqlc.Verification, err error) *StoreMock_FindVerificationByToken_Call {
	_c.Call.Return(verification, err)
	return _c
}

func (_c *StoreMock_FindVerificationByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (sqlc.Verification, error)) *StoreMock_FindVerificationByToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserEmail provides a mock function for the type StoreMock
func (_mock *StoreMock) UpdateUserEmail(ctx context.Context, arg sqlc.UpdateUserEmailParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserEmailParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_UpdateUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserEmail'
type StoreMock_UpdateUserEmail_Call struct {
	*mock.Call
}

// UpdateUserEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateUserEmailParams
func (_e *StoreMock_Expecter) UpdateUserEmail(ctx interface{}, arg interface{}) *StoreMock_UpdateUserEmail_Call {
	return &StoreMock_UpdateUserEmail_Call{Call: _e.mock.On("UpdateUserEmail", ctx, arg)}
}

func (_c *StoreMock_UpdateUserEmail_Call) Run(run func(ctx context.Context, arg sqlc.UpdateUserEmailParams)) *StoreMock_UpdateUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateUserEmailParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateUserEmailParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_UpdateUserEmail_Call) Return(err error) *StoreMock_UpdateUserEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_UpdateUserEmail_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateUserEmailParams) error) *StoreMock_UpdateUserEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserName provides a mock function for the type StoreMock
func (_mock *StoreMock) UpdateUserName(ctx context.Context, arg sqlc.UpdateUserNameParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserNameParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_UpdateUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserName'
type StoreMock_UpdateUserName_Call struct {
	*mock.Call
}

// UpdateUserName is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateUserNameParams
func (_e *StoreMock_Expecter) UpdateUserName(ctx interface{}, arg interface{}) *StoreMock_UpdateUserName_Call {
	return &StoreMock_UpdateUserName_Call{Call: _e.mock.On("UpdateUserName", ctx, arg)}
}

func (_c *StoreMock_UpdateUserName_Call) Run(run func(ctx context.Context, arg sqlc.UpdateUserNameParams)) *StoreMock_UpdateUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateUserNameParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateUserNameParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_UpdateUserName_Call) Return(err error) *StoreMock_UpdateUserName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_UpdateUserName_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateUserNameParams) error) *StoreMock_UpdateUserName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function for the type StoreMock
func (_mock *StoreMock) UpdateUserPassword(ctx context.Context, arg sqlc.UpdateUserPasswordParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserPasswordParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type StoreMock_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateUserPasswordParams
func (_e *StoreMock_Expecter) UpdateUserPassword(ctx interface{}, arg interface{}) *StoreMock_UpdateUserPassword_Call {
	return &StoreMock_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, arg)}
}

func (_c *StoreMock_UpdateUserPassword_Call) Run(run func(ctx context.Context, arg sqlc.UpdateUserPasswordParams)) *StoreMock_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateUserPasswordParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateUserPasswordParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_UpdateUserPassword_Call) Return(err error) *StoreMock_UpdateUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_UpdateUserPassword_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateUserPasswordParams) error) *StoreMock_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyUserEmail provides a mock function for the type StoreMock
func (_mock *StoreMock) VerifyUserEmail(ctx context.Context, arg sqlc.VerifyUserEmailParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for VerifyUserEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.VerifyUserEmailParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_VerifyUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyUserEmail'
type StoreMock_VerifyUserEmail_Call struct {
	*mock.Call
}

// VerifyUserEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.VerifyUserEmailParams
func (_e *StoreMock_Expecter) VerifyUserEmail(ctx interface{}, arg interface{}) *StoreMock_VerifyUserEmail_Call {
	return &StoreMock_VerifyUserEmail_Call{Call: _e.mock.On("VerifyUserEmail", ctx, arg)}
}

func (_c *StoreMock_VerifyUserEmail_Call) Run(run func(ctx context.Context, arg sqlc.VerifyUserEmailParams)) *StoreMock_VerifyUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.VerifyUserEmailParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.VerifyUserEmailParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreMock_VerifyUserEmail_Call) Return(err error) *StoreMock_VerifyUserEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_VerifyUserEmail_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.VerifyUserEmailParams) error) *StoreMock_VerifyUserEmail_Call {
	_c.Call.Return(run)
	return _c
}
