// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gbvillarinho/base-project/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewURLServiceMock creates a new instance of URLServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLServiceMock {
	mock := &URLServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// URLServiceMock is an autogenerated mock type for the URLService type
type URLServiceMock struct {
	mock.Mock
}

type URLServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *URLServiceMock) EXPECT() *URLServiceMock_Expecter {
	return &URLServiceMock_Expecter{mock: &_m.Mock}
}

// GenerateVerificationURL provides a mock function for the type URLServiceMock
func (_mock *URLServiceMock) GenerateVerificationURL(ctx context.Context, token string, flow domain.VerificationFlow) string {
	ret := _mock.Called(ctx, token, flow)

	if len(ret) == 0 {
		panic("no return value specified for GenerateVerificationURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.VerificationFlow) string); ok {
		r0 = returnFunc(ctx, token, flow)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// URLServiceMock_GenerateVerificationURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateVerificationURL'
type URLServiceMock_GenerateVerificationURL_Call struct {
	*mock.Call
}

// GenerateVerificationURL is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - flow domain.VerificationFlow
func (_e *URLServiceMock_Expecter) GenerateVerificationURL(ctx interface{}, token interface{}, flow interface{}) *URLServiceMock_GenerateVerificationURL_Call {
	return &URLServiceMock_GenerateVerificationURL_Call{Call: _e.mock.On("GenerateVerificationURL", ctx, token, flow)}
}

func (_c *URLServiceMock_GenerateVerificationURL_Call) Run(run func(ctx context.Context, token string, flow domain.VerificationFlow)) *URLServiceMock_GenerateVerificationURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.VerificationFlow
		if args[2] != nil {
			arg2 = args[2].(domain.VerificationFlow)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *URLServiceMock_GenerateVerificationURL_Call) Return(s string) *URLServiceMock_GenerateVerificationURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *URLServiceMock_GenerateVerificationURL_Call) RunAndReturn(run func(ctx context.Context, token string, flow domain.VerificationFlow) string) *URLServiceMock_GenerateVerificationURL_Call {
	_c.Call.Return(run)
	return _c
}
