// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gbvillarinho/base-project/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewVerificationServiceMock creates a new instance of VerificationServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationServiceMock {
	mock := &VerificationServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VerificationServiceMock is an autogenerated mock type for the VerificationService type
type VerificationServiceMock struct {
	mock.Mock
}

type VerificationServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *VerificationServiceMock) EXPECT() *VerificationServiceMock_Expecter {
	return &VerificationServiceMock_Expecter{mock: &_m.Mock}
}

// CreateVerification provides a mock function for the type VerificationServiceMock
func (_mock *VerificationServiceMock) CreateVerification(ctx context.Context, params domain.CreateVerificationParams) (*domain.Verification, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerification")
	}

	var r0 *domain.Verification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateVerificationParams) (*domain.Verification, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateVerificationParams) *domain.Verification); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Verification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CreateVerificationParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VerificationServiceMock_CreateVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerification'
type VerificationServiceMock_CreateVerification_Call struct {
	*mock.Call
}

// CreateVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - params domain.CreateVerificationParams
func (_e *VerificationServiceMock_Expecter) CreateVerification(ctx interface{}, params interface{}) *VerificationServiceMock_CreateVerification_Call {
	return &VerificationServiceMock_CreateVerification_Call{Call: _e.mock.On("CreateVerification", ctx, params)}
}

func (_c *VerificationServiceMock_CreateVerification_Call) Run(run func(ctx context.Context, params domain.CreateVerificationParams)) *VerificationServiceMock_CreateVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CreateVerificationParams
		if args[1] != nil {
			arg1 = args[1].(domain.CreateVerificationParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VerificationServiceMock_CreateVerification_Call) Return(verification *domain.Verification, err error) *VerificationServiceMock_CreateVerification_Call {
	_c.Call.Return(verification, err)
	return _c
}

func (_c *VerificationServiceMock_CreateVerification_Call) RunAndReturn(run func(ctx context.Context, params domain.CreateVerificationParams) (*domain.Verification, error)) *VerificationServiceMock_CreateVerification_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeToken provides a mock function for the type VerificationServiceMock
func (_mock *VerificationServiceMock) ExchangeToken(ctx context.Context, token string, expectedFlow domain.VerificationFlow) (*domain.Verification, error) {
	ret := _mock.Called(ctx, token, expectedFlow)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeToken")
	}

	var r0 *domain.Verification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.VerificationFlow) (*domain.Verification, error)); ok {
		return returnFunc(ctx, token, expectedFlow)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.VerificationFlow) *domain.Verification); ok {
		r0 = returnFunc(ctx, token, expectedFlow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Verification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.VerificationFlow) error); ok {
		r1 = returnFunc(ctx, token, expectedFlow)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VerificationServiceMock_ExchangeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeToken'
type VerificationServiceMock_ExchangeToken_Call struct {
	*mock.Call
}

// ExchangeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - expectedFlow domain.VerificationFlow
func (_e *VerificationServiceMock_Expecter) ExchangeToken(ctx interface{}, token interface{}, expectedFlow interface{}) *VerificationServiceMock_ExchangeToken_Call {
	return &VerificationServiceMock_ExchangeToken_Call{Call: _e.mock.On("ExchangeToken", ctx, token, expectedFlow)}
}

func (_c *VerificationServiceMock_ExchangeToken_Call) Run(run func(ctx context.Context, token string, expectedFlow domain.VerificationFlow)) *VerificationServiceMock_ExchangeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.VerificationFlow
		if args[2] != nil {
			arg2 = args[2].(domain.VerificationFlow)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VerificationServiceMock_ExchangeToken_Call) Return(verification *domain.Verification, err error) *VerificationServiceMock_ExchangeToken_Call {
	_c.Call.Return(verification, err)
	return _c
}

func (_c *VerificationServiceMock_ExchangeToken_Call) RunAndReturn(run func(ctx context.Context, token string, expectedFlow domain.VerificationFlow) (*domain.Verification, error)) *VerificationServiceMock_ExchangeToken_Call {
	_c.Call.Return(run)
	return _c
}
