// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BlockUser(ctx context.Context, arg BlockUserParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateVerification(ctx context.Context, arg CreateVerificationParams) error
	DeleteSessionByID(ctx context.Context, id uuid.UUID) error
	DeleteSessionsByUserExceptID(ctx context.Context, arg DeleteSessionsByUserExceptIDParams) error
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteVerification(ctx context.Context, id uuid.UUID) error
	DeleteVerificationsByUserIDAndFlow(ctx context.Context, arg DeleteVerificationsByUserIDAndFlowParams) error
	ExistsByEmail(ctx context.Context, email string) (bool, error)
	FindSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	FindSessionByToken(ctx context.Context, token string) (Session, error)
	FindSessionsByUserID(ctx context.Context, arg FindSessionsByUserIDParams) ([]Session, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (User, error)
	FindValidVerificationByUserIDAndFlow(ctx context.Context, arg FindValidVerificationByUserIDAndFlowParams) (Verification, error)
	FindVerificationByID(ctx context.Context, id uuid.UUID) (Verification, error)
	FindVerificationByToken(ctx context.Context, token string) (Verification, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	VerifyUserEmail(ctx context.Context, arg VerifyUserEmailParams) error
}

var _ Querier = (*Queries)(nil)
