// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, token, device_name, ip_address, user_agent, expires_at, created_at, user_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID         uuid.UUID `json:"id"`
	Token      string    `json:"token"`
	DeviceName string    `json:"device_name"`
	IpAddress  string    `json:"ip_address"`
	UserAgent  string    `json:"user_agent"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Token,
		arg.DeviceName,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UserID,
	)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByID, id)
	return err
}

const deleteSessionsByUserExceptID = `-- name: DeleteSessionsByUserExceptID :exec
DELETE FROM sessions
WHERE user_id = ? AND id != ?
`

type DeleteSessionsByUserExceptIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DeleteSessionsByUserExceptID(ctx context.Context, arg DeleteSessionsByUserExceptIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserExceptID, arg.UserID, arg.ID)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const findSessionByID = `-- name: FindSessionByID :one
SELECT id, token, device_name, ip_address, user_agent, expires_at, created_at, user_id FROM sessions WHERE id = ?
`

func (q *Queries) FindSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, findSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.DeviceName,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const findSessionByToken = `-- name: FindSessionByToken :one
SELECT id, token, device_name, ip_address, user_agent, expires_at, created_at, user_id FROM sessions WHERE token = ?
`

func (q *Queries) FindSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, findSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.DeviceName,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const findSessionsByUserID = `-- name: FindSessionsByUserID :many
SELECT id, token, device_name, ip_address, user_agent, expires_at, created_at, user_id FROM sessions
WHERE user_id = ? AND expires_at > ?
`

type FindSessionsByUserIDParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) FindSessionsByUserID(ctx context.Context, arg FindSessionsByUserIDParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, findSessionsByUserID, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.DeviceName,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
