// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verifications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerification = `-- name: CreateVerification :exec
INSERT INTO verifications (id, flow, token, created_at, expires_at, payload, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateVerificationParams struct {
	ID        uuid.UUID `json:"id"`
	Flow      string    `json:"flow"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Payload   *string   `json:"payload"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.Exec(ctx, createVerification,
		arg.ID,
		arg.Flow,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Payload,
		arg.UserID,
	)
	return err
}

const deleteVerification = `-- name: DeleteVerification :exec
DELETE FROM verifications WHERE id = $1
`

func (q *Queries) DeleteVerification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerification, id)
	return err
}

const deleteVerificationsByUserIDAndFlow = `-- name: DeleteVerificationsByUserIDAndFlow :exec
DELETE FROM verifications
WHERE user_id = $1
  AND flow = $2
  AND expires_at > $3
`

type DeleteVerificationsByUserIDAndFlowParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Flow      string    `json:"flow"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) DeleteVerificationsByUserIDAndFlow(ctx context.Context, arg DeleteVerificationsByUserIDAndFlowParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationsByUserIDAndFlow, arg.UserID, arg.Flow, arg.ExpiresAt)
	return err
}

const findValidVerificationByUserIDAndFlow = `-- name: FindValidVerificationByUserIDAndFlow :one
SELECT id, flow, token, created_at, expires_at, payload, user_id FROM verifications
WHERE user_id = $1
  AND flow = $2
  AND expires_at > $3
ORDER BY created_at DESC
LIMIT 1
`

type FindValidVerificationByUserIDAndFlowParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Flow      string    `json:"flow"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) FindValidVerificationByUserIDAndFlow(ctx context.Context, arg FindValidVerificationByUserIDAndFlowParams) (Verification, error) {
	row := q.db.QueryRow(ctx, findValidVerificationByUserIDAndFlow, arg.UserID, arg.Flow, arg.ExpiresAt)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Flow,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Payload,
		&i.UserID,
	)
	return i, err
}

const findVerificationByID = `-- name: FindVerificationByID :one
SELECT id, flow, token, created_at, expires_at, payload, user_id FROM verifications WHERE id = $1
`

func (q *Queries) FindVerificationByID(ctx context.Context, id uuid.UUID) (Verification, error) {
	row := q.db.QueryRow(ctx, findVerificationByID, id)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Flow,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Payload,
		&i.UserID,
	)
	return i, err
}

const findVerificationByToken = `-- name: FindVerificationByToken :one
SELECT id, flow, token, created_at, expires_at, payload, user_id FROM verifications WHERE token = $1
`

func (q *Queries) FindVerificationByToken(ctx context.Context, token string) (Verification, error) {
	row := q.db.QueryRow(ctx, findVerificationByToken, token)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Flow,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Payload,
		&i.UserID,
	)
	return i, err
}
